### ISSUE TITLE
The BuildListener.buildStarted(Gradle) method has been deprecated. This is scheduled to be removed in Gradle 7.0

### ISSUE THREAD

**Issue by DanielWeigl** [passy/build-time-tracker-plugin#100]
gradle > 6.5 currently throws a warning and will fail to compile after 7.0 with this plugin:

```
The BuildListener.buildStarted(Gradle) method has been deprecated. This is scheduled to be removed in Gradle 7.0. Consult the upgrading guide for further information: https://docs.gradle.org/6.5/userguide/upgrading_version_5.html#apis_buildlistener_buildstarted_and_gradle_buildstarted_have_been_deprecated
        at org.gradle.invocation.DefaultGradle.nagBuildStartedDeprecationIfOverriden(DefaultGradle.java:425)
        at org.gradle.invocation.DefaultGradle.addBuildListener(DefaultGradle.java:415)
        at org.gradle.api.invocation.Gradle$addBuildListener.call(Unknown Source)
        at net.rdrei.android.buildtimetracker.BuildTimeTrackerPlugin.apply(BuildTimeTrackerPlugin.groovy:29)
        at net.rdrei.android.buildtimetracker.BuildTimeTrackerPlugin.apply(BuildTimeTrackerPlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:181)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:51)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:276)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:395)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:387)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:84)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:159)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:156)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:49)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:156)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:136)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$applyLegacyPlugins$2(DefaultPluginRequestApplicator.java:140)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:178)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$applyLegacyPlugins$3(DefaultPluginRequestApplicator.java:138)
```
The problem is at line https://github.com/passy/build-time-tracker-plugin/blob/master/src/main/groovy/net/rdrei/android/buildtimetracker/BuildTimeTrackerPlugin.groovy#L29 and the gradle migration guide is not very helpful:

> APIs BuildListener.buildStarted and Gradle.buildStarted have been deprecated
> These methods currently do not work as expected since the callbacks will never be called after the build has started.
> The methods are being deprecated to avoid confusion.

**Comment by DanielWeigl** [comment]
Here is the commit which deprecated it: https://github.com/gradle/gradle/issues/7613
