### ISSUE TITLE
TrueTimeProvider has moved as of gradle 3.3

### ISSUE THREAD

**Issue by gverwers** [passy/build-time-tracker-plugin#75]
All of the classes using TrueTimeProvider are failing with class not found because TrueTimeProvider has moved from org.gradle.internal to org.gradle.internal.time.    As changing this TrueTimeProvider to it's new package will break all users of prior version of gradle.   I would suggest creating your own implementation of TrueTimeProvider or use the code from TrueTimeProvider.   

Caused by: java.lang.NoClassDefFoundError: org/gradle/internal/TrueTimeProvider
        at net.rdrei.android.buildtimetracker.reporters.CSVReporter.run(CSVReporter.groovy:18)
        at net.rdrei.android.buildtimetracker.reporters.CSVReporter$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at net.rdrei.android.buildtimetracker.TimingRecorder$_buildFinished_closure1.doCall(TimingRecorder.groovy:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by passsy** [comment]
breakes every build

```
...
:app:clean
:clean

BUILD SUCCESSFUL

Total time: 0.893 secs

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify build listener.
```

**Comment by gverwers** [comment]
I don’t think is worth it to use the gradle internal class anymore.

**Comment by passy** [comment]
Hey, I appreciate the report. Given the size of the class, I agree that shipping a custom implementation is probably the best option.

I won't have time to look into this for the next weeks or so. If anyone else wants to work on this, please go ahead. :)
